### ISSUE TITLE
Input box line adjustment issue

### ISSUE THREAD

**Issue by lhypds** [gcc3/simple-ai-chat#176]
![image](https://github.com/gcc3/simple-ai-chat/assets/4526937/5724f38d-06b6-420e-b3ea-237a107ba524)

**Comment by JonnyMc94** [comment]
Hi @lhypds , I would like to work on this! Could you provide more info please?

**Comment by lhypds** [comment]
Thank you for your interests. @JonnyMc94 

When user input some text, normally the `textarea` will grow with the text, however in this case, you can see, the text is overlapped. We want the text always be seen, not hidden inside.

Reproduce:
Copy an image (can be png, jpg), paste into the input area (textarea), it will start uploading. Then you will see the text as above.

Expect Behavior:
After pasting the text is shown inside completely.

Like this:
![image](https://github.com/gcc3/simple-ai-chat/assets/4526937/9605339f-53e3-49f3-8b47-e772b397652b)

There are 3 themes (you can find in `styles/pages` folder.)
This issue only happen in `index.module.css`, default theme.

--
Enjoy the coding! ☺️

**Comment by JonnyMc94** [comment]
@lhypds I am trying to reproduce this issue but I'm facing a problem. When I paste an image into the textbox I'm getting the following error -> 
<img width="666" alt="Screenshot 2023-11-13 at 18 51 15" src="https://github.com/gcc3/simple-ai-chat/assets/73396636/d0f17ca0-aa42-4f0a-a350-181334fc8756">

**Comment by lhypds** [comment]
@JonnyMc94 

It seems that the error message you encountered could be caused by incorrect AWS S3 permissions. If you're running the application on your local machine, make sure that the S3 permissions are correctly set.

If you encounter this error while using `simple-ai.io`, please create a new issue and include steps to reproduce the problem.

To reproduce this issue, both locally and in production, follow these steps:
1. Input some longer text into the textarea.
2. Select all of the text and delete it.
3. Notice that the textarea does not resize to one row as expected.

Here are screenshots demonstrating the issue:

<img width="612" alt="image" src="https://github.com/gcc3/simple-ai-chat/assets/4526937/1b67787a-91b4-481c-8b45-3b598ab50bec">

<img width="638" alt="image" src="https://github.com/gcc3/simple-ai-chat/assets/4526937/9a773522-16a8-4a45-b1e6-fe2300946a3d">

--
Let me know if you still cannot reproduce this issue. 🙂

**Comment by lhypds** [comment]
https://github.com/gcc3/simple-ai-chat/issues/176#issuecomment-1809272321

When I fixing another issue this issue seems also has been fixed, refer PR #202

**Comment by lhypds** [comment]
Fixed by below PR

[#203](https://github.com/gcc3/simple-ai-chat/pull/203)
