### ISSUE TITLE
French language code not found

### ISSUE THREAD

**Issue by FefesG5** [gcc3/simple-ai-chat#841]
![image](https://github.com/gcc3/simple-ai-chat/assets/116435020/2d25728e-3f15-4d7b-9b93-aba99ac15d67)

When I type in :lang use fr as suggested by simple ai chat, I get the bug that fr is not found.

**Comment by lhypds** [comment]
Fixed by updating the doc
https://github.com/gcc3/simple-ai-chat/commit/f2bab6b83a696c82fe199cfde2972d84c0c6ae01

**Comment by lhypds** [comment]
I think need to allow user use only lang code too.

**Comment by lhypds** [comment]
Refix
63dc798aba12ed06d9ca3ba0e878e0624ff95a80
